[tool:pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --tb=short
    --cov=teste_git_hub
    --cov-report=html
    --cov-report=term-missing
    --cov-fail-under=90
testpaths = .
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning