# -*- coding: utf-8 -*-
"""teste_git_hub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZTKLHaPzrTy8tcu3IYFSCefnnVtvIEF
"""

# Este arquivo agora é apenas um script de teste/manual. Não contém mais código Flask.

from agents import agente_revisor

nome_do_repositorio = "LucioFlavioRosa/agent-vinna"

resposta_desing = agente_revisor.executar_analise(
    tipo_analise='pentest', repositorio=nome_do_repositorio)

print(resposta_desing['resultado'])
